### ISSUE TITLE
Crash on 32 bit devices

### ISSUE THREAD

**Issue by mttcrsp** [smartadserver/smart-gdpr-cmp-ios#33]
When generating a consent string on 32 bit devices, iPhone 5 and previous generations, the library crashes due to an integer overflow caused by [this conversion](https://github.com/smartadserver/smart-gdpr-cmp-ios/blob/d651cbb2c42dc119ce155bbf54de457fb41ce928/framework/SmartCMP/Utils/CMPBitUtils.swift#L97) from time interval to integer.

**Comment by riisemichi** [comment]
Same issue here, is there a solution?

**Comment by ncanella** [comment]
I have the same issue too.
Do you think is a possibile solution to avoid multiply/divide the timeIntervalSince1970? 

Like that

    public static func dateToBits(_ date: Date, numberOfBits: Int) -> String {
        precondition(numberOfBits >= 0, "'numberOfBits' must be positive")
		
	    let deciseconds = date.timeIntervalSince1970
        return intToBits(Int(deciseconds.rounded()), numberOfBits: numberOfBits)
    }

    public static func bitsToDate(_ bits: String) -> Date? {
        if let deciseconds = bitsToInt(bits) {
		return Date(timeIntervalSince1970: Double(deciseconds))
        } else {
            return nil
        }
    }

Instad

    public static func dateToBits(_ date: Date, numberOfBits: Int) -> String {
        precondition(numberOfBits >= 0, "'numberOfBits' must be positive")
		
	    let deciseconds = date.timeIntervalSince1970 * 10
        return intToBits(Int(deciseconds.rounded()), numberOfBits: numberOfBits)
    }

    public static func bitsToDate(_ bits: String) -> Date? {
        if let deciseconds = bitsToInt(bits) {
		return Date(timeIntervalSince1970: Double(deciseconds) / 10.0)
        } else {
            return nil
        }
    }

**Comment by PasqualePuzio** [comment]
Same issue here. Had to put in place a very dirty solution: if the app is running in 32 bit mode, the CMP isn't initialized https://stackoverflow.com/questions/20104403/determine-if-ios-device-is-32-or-64-bit

**Comment by lgironditmetaz** [comment]
Hello, thanks for the bug report and sorry for the long delay.

The PR #34 should fix the issue.
Can any of you confirm that it works properly (I have only one 32 bits device and it seems to fix everything on it).

**Comment by lgironditmetaz** [comment]
Fixed in release [Version 5](https://github.com/smartadserver/smart-gdpr-cmp-ios/releases/tag/v5).
